//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Dialogue"",
            ""id"": ""73e1ef3e-7a55-4f9d-8c0b-ffaa5ad2e768"",
            ""actions"": [
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""1e84c8b2-53f9-4df3-b825-7983539e9040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""one"",
                    ""type"": ""Button"",
                    ""id"": ""25552b8a-f4ce-4daa-a8f4-94225674ef1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""two"",
                    ""type"": ""Button"",
                    ""id"": ""084d6802-3085-4839-a1c4-2f10b6b4264f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""three"",
                    ""type"": ""Button"",
                    ""id"": ""202125f3-8c7b-42ff-830d-a7c6a2e1167e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""four"",
                    ""type"": ""Button"",
                    ""id"": ""4e5df10a-953e-4d2d-bfca-948b7e1bc5a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""five"",
                    ""type"": ""Button"",
                    ""id"": ""aacbf4ef-9141-4593-82b3-fb61e1630670"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""six"",
                    ""type"": ""Button"",
                    ""id"": ""4e00bbdf-e5ac-4e75-a61f-bcdebc0eb7f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d1e902f1-3fae-4871-9e93-0c86172828c9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""115444a2-d426-462d-8cdc-8ee222880fa9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""one"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77c85185-49a9-4181-8c9f-2adaffbad5be"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6715317f-b51f-4a86-a065-9a499824b07c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08ea0f28-5551-4d4e-8393-9ec8efde6731"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7976acb9-2fad-4125-9da0-7f6172ac97a2"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b821fe4a-2bb0-4e34-9149-83a7a2a55cd8"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dialogue
        m_Dialogue = asset.FindActionMap("Dialogue", throwIfNotFound: true);
        m_Dialogue_Next = m_Dialogue.FindAction("Next", throwIfNotFound: true);
        m_Dialogue_one = m_Dialogue.FindAction("one", throwIfNotFound: true);
        m_Dialogue_two = m_Dialogue.FindAction("two", throwIfNotFound: true);
        m_Dialogue_three = m_Dialogue.FindAction("three", throwIfNotFound: true);
        m_Dialogue_four = m_Dialogue.FindAction("four", throwIfNotFound: true);
        m_Dialogue_five = m_Dialogue.FindAction("five", throwIfNotFound: true);
        m_Dialogue_six = m_Dialogue.FindAction("six", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dialogue
    private readonly InputActionMap m_Dialogue;
    private IDialogueActions m_DialogueActionsCallbackInterface;
    private readonly InputAction m_Dialogue_Next;
    private readonly InputAction m_Dialogue_one;
    private readonly InputAction m_Dialogue_two;
    private readonly InputAction m_Dialogue_three;
    private readonly InputAction m_Dialogue_four;
    private readonly InputAction m_Dialogue_five;
    private readonly InputAction m_Dialogue_six;
    public struct DialogueActions
    {
        private @Controls m_Wrapper;
        public DialogueActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Next => m_Wrapper.m_Dialogue_Next;
        public InputAction @one => m_Wrapper.m_Dialogue_one;
        public InputAction @two => m_Wrapper.m_Dialogue_two;
        public InputAction @three => m_Wrapper.m_Dialogue_three;
        public InputAction @four => m_Wrapper.m_Dialogue_four;
        public InputAction @five => m_Wrapper.m_Dialogue_five;
        public InputAction @six => m_Wrapper.m_Dialogue_six;
        public InputActionMap Get() { return m_Wrapper.m_Dialogue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueActions instance)
        {
            if (m_Wrapper.m_DialogueActionsCallbackInterface != null)
            {
                @Next.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnNext;
                @Next.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnNext;
                @Next.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnNext;
                @one.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnOne;
                @one.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnOne;
                @one.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnOne;
                @two.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnTwo;
                @two.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnTwo;
                @two.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnTwo;
                @three.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnThree;
                @three.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnThree;
                @three.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnThree;
                @four.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFour;
                @four.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFour;
                @four.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFour;
                @five.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFive;
                @five.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFive;
                @five.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnFive;
                @six.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnSix;
                @six.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnSix;
                @six.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnSix;
            }
            m_Wrapper.m_DialogueActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Next.started += instance.OnNext;
                @Next.performed += instance.OnNext;
                @Next.canceled += instance.OnNext;
                @one.started += instance.OnOne;
                @one.performed += instance.OnOne;
                @one.canceled += instance.OnOne;
                @two.started += instance.OnTwo;
                @two.performed += instance.OnTwo;
                @two.canceled += instance.OnTwo;
                @three.started += instance.OnThree;
                @three.performed += instance.OnThree;
                @three.canceled += instance.OnThree;
                @four.started += instance.OnFour;
                @four.performed += instance.OnFour;
                @four.canceled += instance.OnFour;
                @five.started += instance.OnFive;
                @five.performed += instance.OnFive;
                @five.canceled += instance.OnFive;
                @six.started += instance.OnSix;
                @six.performed += instance.OnSix;
                @six.canceled += instance.OnSix;
            }
        }
    }
    public DialogueActions @Dialogue => new DialogueActions(this);
    public interface IDialogueActions
    {
        void OnNext(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
    }
}
